# This is a basic workflow to help you get started with Actions

name: Check IPs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          mkdir -p outputs
          chmod +x check.sh convert_to_html.sh
          wget -O iplist.txt https://raw.seagulls.eu.org/tonyshaoxu/Netflix_HK_DNS/refs/heads/main/outputs/accessible_ips.txt?token=private
          #./check.sh | tee ./outputs/result.txt
          #./convert_to_html.sh ./outputs/result.txt ./outputs/index.html
          ./check.sh | sort -t . -k1,1n -k2,2n -k3,3n -k4,4n | tee ./outputs/result.txt
          cat ./outputs/result.txt | grep Residential/Other | tee ./outputs/residential.txt
          cat ./outputs/result.txt | grep Mobile | tee ./outputs/mobile.txt
          cat ./outputs/residential.txt ./outputs/mobile.txt | sort -t . -k1,1n -k2,2n -k3,3n -k4,4n | awk -F', ' '{print $1","$2","$(NF-1)","$NF}'  > temp.txt
          ./convert_to_html.sh temp.txt ./outputs/all.html
          cat ./outputs/result.txt | grep -v Mobile | grep -v Residential/Other | sort -t . -k1,1n -k2,2n -k3,3n -k4,4n | awk -F', ' '{print $1","$2","$(NF-1)","$NF}' > temp2.txt
          ./convert_to_html.sh temp2.txt ./outputs/other.html
          cat ./outputs/residential.txt ./outputs/mobile.txt | sort -t . -k1,1n -k2,2n -k3,3n -k4,4n | awk -F', ' '{print $1","$2","$(NF-1)","$NF}' | grep -w "REGION: Hong Kong"  > hk.txt
          ./convert_to_html.sh hk.txt ./outputs/index.html
          rm -f *.txt
          
      - name: Commit all files
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "无文件变动，跳过提交"
            exit 0  # 无错误退出
          else
            git config --global user.name "GitHub Actions Bot"
            git config --global user.email "actions@github.com"
            git add ./outputs
            git commit -m "Auto-commit generated file [skip ci]"
            git push
          fi
